Algoritmo "Entrada e Saida de Dados"

// Descrição   : "Entrada e Saida de Dados"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/04/2021
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o seu nome:")
   leia(nome)
   escreval("Digite a sua nota:")
   leia(nota)
   
   escreval("o nome digitado foi: ", nome)
   escreval("a nota digitada foi: ", nota)

Fimalgoritmo